// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function InstallWine() {
  return window['go']['main']['App']['InstallWine']();
}

export function SelectIcon() {
  return window['go']['main']['App']['SelectIcon']();
}

export function SelectInstaller() {
  return window['go']['main']['App']['SelectInstaller']();
}

export function WineStatus() {
  return window['go']['main']['App']['WineStatus']();
}
