// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateShortcut(arg1:main.DesktopRequest):Promise<main.OperationResult>;

export function InstallWine():Promise<main.OperationResult>;

export function RunInstaller(arg1:string):Promise<main.OperationResult>;

export function RunTarget(arg1:string):Promise<main.OperationResult>;

export function SelectExecutable():Promise<string>;

export function SelectIcon():Promise<string>;

export function SelectInstaller():Promise<string>;

export function WineStatus():Promise<main.WineStatus>;
